name: goldidate
description: Goldidate Flutter based application for android and ios

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  font_awesome_flutter: ^9.0.0
  otp_text_field: ^1.1.1

  mobile_number: ^1.0.4
  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  cloud_firestore: ^2.2.1
  google_sign_in: ^5.0.4
  flutter_login_facebook: ^1.0.1
  adobe_xd: ^2.0.0+1
  swipe_cards: ^0.1.0
  auto_size_text: ^2.1.0
  syncfusion_flutter_sliders: ^19.2.60
  syncfusion_flutter_core: ^19.2.60
  url_launcher:
  carousel_slider: ^4.0.0
  flutter_swipable: ^0.1.1
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
        - asset: assets/fonts/SFProDisplay-Black_1.ttf
        - asset: assets/fonts/SFProDisplay-Bold_1.ttf
        - asset: assets/fonts/SFProDisplay-Heavy_1.ttf
        - asset: assets/fonts/SFProDisplay-Light_1.ttf
        - asset: assets/fonts/SFProDisplay-Medium_1.ttf
        - asset: assets/fonts/SFProDisplay-Regular_1.ttf
        - asset: assets/fonts/SFProDisplay-Semibold_3.ttf
        - asset: assets/fonts/SFProDisplay-Thin_1.ttf
        - asset: assets/fonts/SFProDisplay-Ultralight_1.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
